/* 즐겨찾기 */
CREATE TABLE BOOKMARK (
	CONTEST_NUM NUMBER NOT NULL, /* 공모전 번호 */
	USER_ID VARCHAR2(30) NOT NULL /* 아이디 */
);


/* 주석 */
COMMENT ON TABLE BOOKMARK IS '즐겨찾기 테이블';

COMMENT ON COLUMN BOOKMARK.CONTEST_NUM IS '공모전 번호';

COMMENT ON COLUMN BOOKMARK.USER_ID IS '아이디';
