/* 공모 */
CREATE TABLE CONTEST (
   CONTEST_NUM NUMBER NOT NULL, /* 공모 번호 */
   CONTEST_TITLE VARCHAR2(100) NOT NULL, /* 공모 제목 */
   CONTEST_CONTENTS VARCHAR2(1000) NOT NULL, /* 공모 내용 */
   CONTEST_SPONSOR VARCHAR2(50) NOT NULL, /* 공모 주최 */
   CONTEST_FIELD VARCHAR2(100) NOT NULL, /* 공모 분야 */
   CONTEST_BENEFIT VARCHAR2(100) NOT NULL, /* 공모 혜택 */
   DUE_DATE VARCHAR2(30) NOT NULL, /* 마감 날짜 */
   CONTEST_FILE VARCHAR2(100), /* 첨부파일 */
   USER_ID VARCHAR2(30) NOT NULL, /* 아이디 */
   GROUP_NUM VARCHAR2(12) NOT NULL, /* 사업자번호 */
   ADDRESS VARCHAR2(100) NOT NULL, /* 주소 */
   BOOKMARK_COUNT NUMBER NOT NULL /* 즐겨찾기 수 */
);


/* 제약 */
ALTER TABLE CONTEST ADD CONSTRAINT PK_CONTEST PRIMARY KEY (CONTEST_NUM);


/* 주석 */
COMMENT ON TABLE CONTEST IS '공모전 테이블';

COMMENT ON COLUMN CONTEST.CONTEST_NUM IS '공모 번호';

COMMENT ON COLUMN CONTEST.CONTEST_TITLE IS '제목 최소 10자리';

COMMENT ON COLUMN CONTEST.CONTEST_CONTENTS IS '공모 내용';

COMMENT ON COLUMN CONTEST.CONTEST_SPONSOR IS '공모 주최';

COMMENT ON COLUMN CONTEST.CONTEST_FIELD IS '공모 분야';

COMMENT ON COLUMN CONTEST.CONTEST_BENEFIT IS '공모 혜택';

COMMENT ON COLUMN CONTEST.DUE_DATE IS '마감 날짜';

COMMENT ON COLUMN CONTEST.CONTEST_FILE IS '첨부파일';

COMMENT ON COLUMN CONTEST.USER_ID IS '아이디';

COMMENT ON COLUMN CONTEST.GROUP_NUM IS '사업자 번호';

COMMENT ON COLUMN CONTEST.ADDRESS IS '주소';

COMMENT ON COLUMN CONTEST.BOOKMARK_COUNT IS '즐겨찾기 수';