/* 댓글테이블 */
CREATE TABLE reply (
	BOARD_ID CHAR(1) NOT NULL, /* 게시판아이디 */
	BOARD_NUM NUMBER(5) NOT NULL, /* 게시글번호 */
	REPLY_NUM NUMBER NOT NULL, /* 댓글번호 */
	REPLY_DATE VARCHAR2(30) NOT NULL, /* 작성날짜 */
	USER_ID VARCHAR2(60) NOT NULL, /* 작성자 */
	USER_NICKNAME VARCHAR2(16) NOT NULL, /* 닉네임 */
	REPLY_CONTENTS VARCHAR2(300) NOT NULL, /* 댓글내용 */
	REPORT_COUNT NUMBER /* 신고수 */
);


/* 제약 */
ALTER TABLE reply ADD CONSTRAINT PK_reply PRIMARY KEY (BOARD_ID, BOARD_NUM, REPLY_NUM);

ALTER TABLE reply ADD CONSTRAINT FK_BOARD_TO_reply FOREIGN KEY (BOARD_ID, BOARD_NUM)
		REFERENCES BOARD (BOARD_ID, BOARD_NUM);


/* 주석 */
COMMENT ON TABLE reply IS '댓글테이블';

COMMENT ON COLUMN reply.BOARD_ID IS '게시판아이디';

COMMENT ON COLUMN reply.BOARD_NUM IS '게시글번호';

COMMENT ON COLUMN reply.REPLY_NUM IS '댓글번호';

COMMENT ON COLUMN reply.REPLY_DATE IS '작성날짜';

COMMENT ON COLUMN reply.USER_ID IS '작성자';

COMMENT ON COLUMN reply.USER_NICKNAME IS '닉네임';

COMMENT ON COLUMN reply.REPLY_CONTENTS IS '댓글내용';

COMMENT ON COLUMN reply.REPORT_COUNT IS '신고수';
