/* 공모 의뢰 */
CREATE TABLE REQUEST (
	CONTEST_TITLE VARCHAR2(100) NOT NULL, /* 공모 제목 */
	CONTEST_SPONSOR VARCHAR2(50) NOT NULL, /* 공모 주최 */
	CONTEST_FIELD VARCHAR2(100), /* 공모 분야 */
	CONTEST_BENEIT VARCHAR2(100) NOT NULL, /* 공모 혜택 */
	DUE_DATE VARCHAR2(30) NOT NULL, /* 마감 날짜 */
	USER_ID VARCHAR2(30) NOT NULL, /* 아이디 */
	GROUP_NUM NUMBER(10) NOT NULL, /* 사업자번호 */
	CONTEST_CONTENTS VARCHAR2(1000), /* 공모 내용 */
	CONTEST_FILE VARCHAR2(100) /* 첨부파일 */
);


/* 주석 */
COMMENT ON TABLE REQUEST IS '공모 의뢰 테이블';

COMMENT ON COLUMN REQUEST.CONTEST_TITLE IS '공모 제목';

COMMENT ON COLUMN REQUEST.CONTEST_SPONSOR IS '공모 주최';

COMMENT ON COLUMN REQUEST.CONTEST_FIELD IS '공모 분야';

COMMENT ON COLUMN REQUEST.CONTEST_BENEIT IS '공모 혜택';

COMMENT ON COLUMN REQUEST.DUE_DATE IS '마감 날짜';

COMMENT ON COLUMN REQUEST.USER_ID IS '아이디';

COMMENT ON COLUMN REQUEST.GROUP_NUM IS '사업자번호';

COMMENT ON COLUMN REQUEST.CONTEST_CONTENTS IS '공모 내용';

COMMENT ON COLUMN REQUEST.CONTEST_FILE IS '첨부파일';