/* 회원 */
CREATE TABLE USERS(
   USER_ID VARCHAR2(30) NOT NULL, /* 아이디 */
   USER_PW VARCHAR2(20) NOT NULL, /* 비밀번호 */
   USER_NICKNAME VARCHAR2(16) NOT NULL, /* 닉네임 */
   USER_NAME VARCHAR2(20) NOT NULL, /* 이름 */
   USER_PHONE1 VARCHAR2(11) NOT NULL, /* 휴대폰번호 */
   USER_PHONE2 VARCHAR2(15), /* 비상연락처 */
   USER_FIELD VARCHAR2(20), /* 관심분야 */
   USER_GRADE VARCHAR2(1) NOT NULL, /* 등급 */
   USER_EMAIL VARCHAR2(40), /* 이메일 */
   USER_GETMAIL VARCHAR2(1) NOT NULL, /* 메일수신여부 */
   USER_GETSMS VARCHAR2(1) NOT NULL, /* 문자수신여부 */
   CONTEST_SPONSOR VARCHAR2(50), /* 단체명 */
   GROUP_NUM NUMBER(10) /* 사업자번호 */
);


/* 제약 */
ALTER TABLE USERS ADD CONSTRAINT PK_USER PRIMARY KEY (USER_ID);


/* 주석 */
COMMENT ON TABLE USERS IS '회원 테이블';

COMMENT ON COLUMN USERS.USER_ID IS '아이디';

COMMENT ON COLUMN USERS.USER_PW IS '비밀번호';

COMMENT ON COLUMN USERS.USER_NICKNAME IS '닉네임';

COMMENT ON COLUMN USERS.USER_NAME IS '이름';

COMMENT ON COLUMN USERS.USER_PHONE1 IS '휴대폰번호';

COMMENT ON COLUMN USERS.USER_PHONE2 IS '비상연락처';

COMMENT ON COLUMN USERS.USER_FIELD IS '관심분야';

COMMENT ON COLUMN USERS.USER_GRADE IS '등급';

COMMENT ON COLUMN USERS.USER_EMAIL IS '이메일';

COMMENT ON COLUMN USERS.USER_GETMAIL IS '메일수신여부';

COMMENT ON COLUMN USERS.USER_GETSMS IS '문자수신여부';

COMMENT ON COLUMN USERS.CONTEST_SPONSOR IS '단체명';

COMMENT ON COLUMN USERS.GROUP_NUM IS '사업자번호';