/* 투표 */
CREATE TABLE VOTE (
	CONTEST_NUM NUMBER NOT NULL, /* 공모전 번호 */
	WORK_NUM NUMBER NOT NULL, /* 공모자료 번호 */
	USER_ID VARCHAR2(30) NOT NULL /* 아이디 */
);


/* 주석 */
COMMENT ON TABLE VOTE IS '좋아요 테이블';

COMMENT ON COLUMN VOTE.CONTEST_NUM IS '공모전 번호';

COMMENT ON COLUMN VOTE.WORK_NUM IS '공모자료 번호';

COMMENT ON COLUMN VOTE.USER_ID IS '아이디';