/* 작품 */
CREATE TABLE WORK (
   CONTEST_NUM NUMBER NOT NULL, /* 공모번호 */
   WORK_NUM INTEGER NOT NULL, /* 작품번호 */
   USER_ID VARCHAR2(30) NOT NULL, /* 아이디 */
   USER_NICKNAME VARCHAR2(16) NOT NULL, /* 닉네임 */
   WORK_TITLE VARCHAR2(100) NOT NULL, /* 작품 제목 */
   WORK_CONTENT VARCHAR2(1000), /* 작품 내용 */
   WORK_PICTURE VARCHAR2(100) NOT NULL, /* 작품 대표사진 */
   WORK_FILE VARCHAR2(100) NOT NULL, /* 작품 파일 */
   VOTE_COUNT INTEGER NOT NULL, /* 투표 수 */
   REPORT_COUNT INTEGER NOT NULL, /* 신고 수 */
   SUB_DATE VARCHAR2(30), /* 제출 날짜 */
   PRIZE VARCHAR2(20) /* 수상 */
);


/* 제약 */
ALTER TABLE WORK ADD CONSTRAINT PK_WORK PRIMARY KEY (CONTEST_NUM,WORK_NUM);


/* 주석 */
COMMENT ON TABLE WORK IS '사용자가 등록한 작품들을 관리하는 테이블';

COMMENT ON COLUMN WORK.CONTEST_NUM IS '공모전 고유번호';

COMMENT ON COLUMN WORK.WORK_NUM IS '작품 고유번호';

COMMENT ON COLUMN WORK.USER_ID IS '작품을 등록한 사용자의 아이디';

COMMENT ON COLUMN WORK.USER_NICKNAME IS '작품을 등록한 사용자의 닉네임';

COMMENT ON COLUMN WORK.WORK_TITLE IS '작품 작성 시 제목';

COMMENT ON COLUMN WORK.WORK_CONTENT IS '작품 작성 시 내용';

COMMENT ON COLUMN WORK.WORK_PICTURE IS '대표사진 등록할 때 업로드 하는 파일명';

COMMENT ON COLUMN WORK.WORK_FILE IS '작품 등록할 때 업로드 하는 파일명';

COMMENT ON COLUMN WORK.VOTE_COUNT IS '해당 작품이 받은 UP(투표) 수';

COMMENT ON COLUMN WORK.REPORT_COUNT IS '해당 작품이 받은 신고 수';

COMMENT ON COLUMN WORK.PRIZE IS '해당 작품이 받은 상';